## Data Preprocessing dengan Scikit-Learn
Source : [Indonesia Belajar](https://youtu.be/smNnhEd26Ek)
### Sample Dataset
- Pada sample dataset kali ini terdiri dari 4 baris dataset yang masing-masingnya terdiri dari 3 features
- Fungsi.shape digunakan untuk melihat dimensi dataset. Output bernilai 4,3 berarti memiliki 4 baris dan 3 features.

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [2]:
sample_data.shape

(4, 3)

### Binarisation
- Binarisation hanya menghasilkan keluaran 0 dan 1 saja.
- Binarizer dapat ditentukan menggunakan fungsi preprocessing.Binarizer()
  - Parameter threshold menentukan nilai mana yang akan dijadikan 0 karena sisanya akan dijadikan 1.
- Fungsi transform() digunakan untuk mengubah sample_data menjadi bilangan yang binarised.

In [3]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [4]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

### Scaling
- Bertujuan untuk menghasilkan data numerik dalam jangkauan tertentu
- Dengan menggunakan fungsi preprocessing.MinMaxScaler().
  - Parameter feature_range digunakan untuk menentukan jangkauan scaling.
- Setelahnya kita sesuaikan sample_data dengan scaler tadi menggunakan fungsi fit().
- Terakhir transform sample_data menggunakan method transform().
- Penyingkatan cara kedua dan ketiga bisa dilakukan dengan menggunkan method fit_transform().

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [6]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [7]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

### L1 Normalisation: Least Absolute Deviations
Referensi: https://en.wikipedia.org/wiki/Least_absolute_deviations

- Untuk melakukan normaliasi nilai numerik dapat menggunakan fungsi preprocessing.normalize().

In [8]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [9]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

### L2 Normalisation: Least Squares
Referensi: https://en.wikipedia.org/wiki/Least_squares
- Untuk melakukan normaliasi nilai numerik dapat menggunakan fungsi preprocessing.normalize().

In [10]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [11]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])